#!/bin/bash

pipenv install
if [ $? -ne 0 ]; then
    echo "You may need to install pipenv, or check that the correct Python version is available"
    exit 1
fi

mkdir input
mkdir output
mkdir output/collect_video_data
mkdir output/view_data
